### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by nazar-pc** [WyriHaximusNet/docker-php#9]
Please consider using automated builds for these images, so that people can somewhat trust that contents of this repository corresponds to images on Docker Hub.
I'd like to use this, but will not unless it is an automated build.

**Comment by WyriHaximus** [comment]
Currently this project uses CircleCI, because of the flexibility it offers over automated builds from Docker Hub, to build and push images to docker hub. All of that is available in the open at https://github.com/WyriHaximusNet/docker-php (and through the commit status). The configuration of the build is also in this repository at [`.circleci/config.yml`](https://github.com/WyriHaximusNet/docker-php/blob/master/.circleci/config.yml)

**Comment by WyriHaximus** [comment]
I appreciate your input and I've set down with CircleCI to see if their UI can be improved and one of my co-workers @renatomefi who initially set up the build process this repository is based on to see how we can show how to verify the images.

1. So the way to verify a the image now is to go to CircleCI: https://circleci.com/gh/WyriHaximusNet/docker-php
2. Go to the latest `build-zts` (or `nts` depending on which one to verify)
3. Scroll to `cat ./tmp/build-zts.tags | xargs -I % docker inspect --format='%={{.Id}}:{{index .ContainerConfig.Env 7}}' %z` and click it. This will show the sha256 signatures of each image build in that job
4. Docker pull the image you want, for example `docker pull wyrihaximusnet/php:7.3-zts-alpine3.9`
5. Inspect the pulled image and compare the sha256 ID from CircleCI with the one of the pulled image like: `docker inspect wyrihaximusnet/php:7.3-zts-alpine3.9 -f '{{.Id}}'`

**Comment by renatomefi** [comment]
Hello @nazar-pc,

I want to point that you might be missing a few things, automated build does **not** imply the account admin can't push images, even replace tags and etc.
Just a few, very few repos actually used signed images (content trust) which we could help your concern.
So you might have a illusion of being safe while majority of the images you're currently used aren't any safer than this.

I hope this helps you understand the problem is bigger and if you still don't want to use those images it shouldn't be because of content trust.

**Comment by nazar-pc** [comment]
Yes, thanks for detailed explanation, makes sense to me
